[package]
name = "yyid"
version = "0.2.4"
authors = ["Christoph Grabo <asaaki@mannaz.cc>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/asaaki/yyid.rs"
documentation = "http://asaaki.github.io/yyid.rs/yyid/index.html"
repository = "https://github.com/asaaki/yyid.rs"
description = """
YYID generator (random tokens like UUIDv4)
"""
keywords = ["yyid", "uuid", "random", "token"]

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
libc = "0.2"
rand = "0.3"
