name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.5
    - uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - uses: Swatinem/rust-cache@v1

    - name: CI run
      run: make ci
